apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-kasandra-chumpitaz-hpa
  namespace: kasandra-chumpitaz-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kasandra-chumpitaz-backend-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 50
