apiVersion: v1
kind: Service
metadata:
  name: kasandra-chumpitaz-frontend-service
  namespace: kasandra-chumpitaz-namespace
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4200
      nodePort: 30002
  selector:
    app: frontend-kasandra-chumpitaz-deployment
